### ISSUE TITLE
Support for 2.5D/3D geometry removed?

### ISSUE THREAD

**Issue by chau-intl** [elpaso/quickwkt#18]
I have previously been able to insert 2.5D/3D WKT strings into QuickWKT and have the resulting 2D geometry visualised in QGIS. Now it just creates a layer without geometry.

**Comment by elpaso** [comment]
I didn't (intentionally) remove that feature and I can't imagine what recent modifications could have broken it.

**Comment by chau-intl** [comment]
Then it might be QGIS being unwilling to accept certain geometries with Z-values - i'll look in that direction instead.

My simple test cases:

Doesn't work: POLYGON((1 1 0,1 2 0, 2 2 0, 2 1 0)) 
Does work: POLYGON((1 1,1 2, 2 2, 2 1))

Does work?!: POINT(0 0 0)

**Comment by chau-intl** [comment]
I have tried adding the above geometry to a layer without using QuickWKT, and since it doesn't work either, I'll close this issue.
