### ISSUE TITLE
'MULTI' geometry WKT containing spaces raised as non supported WKT type

### ISSUE THREAD

**Issue by marthomas** [elpaso/quickwkt#19]
Entering the following well known text in the QuickWKT dialog and clicking 'OK':

WKT | REMARK | RESULT
----------|----------|----------
MULTIPOINT((1 1 ),(0 0)) | no space between multi geometries | works fine |
MULTIPOINT((1 1 ), (0 0)) | space between multi geometries | throws unsupported WKT type warning |

QuickWKT version
2.5
QGIS version
2.10.0-Pisa
QGIS code revision
exported
Compiled against Qt
4.8.6
Running against Qt
4.8.6
Compiled against GDAL/OGR
1.11.2
Running against GDAL/OGR
1.11.2
Compiled against GEOS
3.4.2-CAPI-1.8.2
Running against GEOS
3.4.2-CAPI-1.8.2 r3921
PostgreSQL Client Version
9.4.1
SpatiaLite Version
4.1.1
QWT Version
5.2.3
PROJ.4 Version
480
QScintilla2 Version
2.8.4

**Comment by elpaso** [comment]
Cannot reproduce in latest version.
