### ISSUE TITLE
Update link on About tab

### ISSUE THREAD

**Issue by bladeoflight16** [elpaso/quickwkt#24]
The About tab in the plug in contains a link named "Public Home Page." This currently links to a blog post from 2010, which itself contains a broken link to the plug in repository page. It seems to me that it would be better to link to either the [plug in repository page](http://plugins.qgis.org/plugins/QuickWKT/) directly or this repository, depending on where you would rather have them land. At the very least, update the link on the blog post.

**Comment by elpaso** [comment]
Thanks. I updated the link to the new official repo in the blog post.
